import { loadAssets } from "./assets.js";
import { HOTBAR_SIZE, REACH, TILE_SIZE, WORLD_HEIGHT, WORLD_WIDTH } from "./config.js";
import { ITEM_DEFS, TILE_DEFS } from "./definitions.js";
import { addItem, countItem, createInventory, removeItem } from "./inventory.js";
import { createPlayer, playerOverlapsTile, updatePlayer } from "./player.js";
import { drawCrosshair, drawHotbar, drawHud, drawPlayer, drawShop, drawSky, drawTile, shopOfferAt } from "./ui.js";
import { World, generateWorld } from "./world.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import { get, onDisconnect, onValue, ref, remove, runTransaction, set, update } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-database.js";
import { auth, database, firebaseConfigured } from "./firebase.js";

const canvas = document.querySelector("#game");
const context = canvas.getContext("2d");
const loadingCard = document.querySelector("#loading-card");
const loadingTitle = document.querySelector("#loading-title");
const loadingMessage = document.querySelector("#loading-message");
const shopButton = document.querySelector("#shop-button");
const leaveButton = document.querySelector("#leave-button");
const params = new URLSearchParams(window.location.search);
const worldKey = params.get("world");
const requestedName = params.get("name") || worldKey;
let assets, world, inventory, player, user, username = "Explorer", worldStateRef, playerStateRef, presenceRef;
let running = false, lastFrame = 0, lastPlayerSave = 0, lastPlantCheck = 0, selectedSlot = 0, shopOpen = false, shopLayout = null, pendingWorldChange = false, remotePlayers = {};
const camera = { x: 0, y: 0 };
const input = { left: false, right: false, jumpPressed: false, pointerDown: false, pointer: { x: 0, y: 0 } };
const breaking = { active: false, x: -1, y: -1, startedAt: 0, progress: 0 };
const toast = { message: "", timeLeft: 0 };

function fail(message) { loadingTitle.textContent = "Could not enter world"; loadingMessage.textContent = message; loadingCard.classList.remove("is-hidden"); }
function notify(message) { toast.message = message; toast.timeLeft = 2.4; }
function resize() { canvas.width = Math.max(320, window.innerWidth); canvas.height = Math.max(320, window.innerHeight); context.imageSmoothingEnabled = false; }
function stopBreaking() { Object.assign(breaking, { active: false, progress: 0, x: -1, y: -1 }); }
function setShopOpen(open) { shopOpen = open; shopButton.setAttribute("aria-expanded", String(open)); shopButton.textContent = open ? "Close market" : "Sky Market"; stopBreaking(); }
function pointerPosition(event) { const bounds = canvas.getBoundingClientRect(); input.pointer.x = (event.clientX - bounds.left) * (canvas.width / bounds.width); input.pointer.y = (event.clientY - bounds.top) * (canvas.height / bounds.height); }
function tileTarget() { const x = Math.floor((input.pointer.x + camera.x) / TILE_SIZE), y = Math.floor((input.pointer.y + camera.y) / TILE_SIZE), inBounds = x >= 0 && x < WORLD_WIDTH && y >= 0 && y < WORLD_HEIGHT; const reachable = Math.hypot(x * TILE_SIZE + TILE_SIZE / 2 - (player.x + player.width / 2), y * TILE_SIZE + TILE_SIZE / 2 - (player.y + player.height / 2)) <= REACH; return { x, y, inBounds, reachable, tileId: inBounds ? world.get(x, y) : 0 }; }
function dropsFor(definition) { return (definition.harvest?.drops ?? definition.drops ?? []).map((drop) => { if (drop.chance && Math.random() > drop.chance) return null; return { item: drop.item, amount: drop.min ? Math.floor(Math.random() * (drop.max - drop.min + 1)) + drop.min : drop.count ?? 1 }; }).filter(Boolean); }
async function mutateWorld(mutator) { if (pendingWorldChange) return false; pendingWorldChange = true; try { const result = await runTransaction(worldStateRef, (current) => { const next = World.fromSave(current ?? {}) ?? generateWorld(); mutator(next); return next.serialize(); }); const updatedWorld = World.fromSave(result.snapshot.val()); if (updatedWorld) world = updatedWorld; return result.committed; } catch { notify("World update failed. Check your connection."); return false; } finally { pendingWorldChange = false; } }
async function savePlayerState() { if (playerStateRef && player && inventory) await set(playerStateRef, { inventory, player: { x: player.x, y: player.y }, selectedSlot, updatedAt: Date.now() }).catch(() => {}); }
async function updatePresence() { if (presenceRef && player) await set(presenceRef, { username, x: Math.round(player.x), y: Math.round(player.y), facing: player.facing, updatedAt: Date.now() }).catch(() => {}); }
async function completeBreak(target) { const definition = TILE_DEFS[target.tileId]; if (!definition || definition.unbreakable) return; const committed = await mutateWorld((next) => { if (next.get(target.x, target.y) === target.tileId) { next.set(target.x, target.y, 0); next.removePlant(target.x, target.y); } }); if (!committed) return; dropsFor(definition).forEach((drop) => addItem(inventory, drop.item, drop.amount)); notify(definition.harvest ? `Harvested ${definition.name}!` : `Mined ${definition.name}.`); savePlayerState(); }
function updateBreaking(now, target) { if (!input.pointerDown || !target.inBounds || !target.reachable || !target.tileId || shopOpen || pendingWorldChange) { stopBreaking(); return; } const definition = TILE_DEFS[target.tileId]; if (!definition || definition.unbreakable) { stopBreaking(); return; } if (!breaking.active || breaking.x !== target.x || breaking.y !== target.y) Object.assign(breaking, { active: true, x: target.x, y: target.y, startedAt: now, progress: 0 }); breaking.progress = (now - breaking.startedAt) / definition.breakTime; if (breaking.progress >= 1) { completeBreak(target); stopBreaking(); } }
async function placeSelected() { if (shopOpen || pendingWorldChange) return; const target = tileTarget(), slot = inventory[selectedSlot]; if (!target.inBounds || !target.reachable || !slot) return; const item = ITEM_DEFS[slot.itemId]; if (!item.placesTile) { notify("That item cannot be placed."); return; } if (target.tileId) { notify("That space is occupied."); return; } if (playerOverlapsTile(player, target.x, target.y)) { notify("Give yourself a little room."); return; } if (!removeItem(inventory, slot.itemId, 1)) return; const committed = await mutateWorld((next) => { if (next.get(target.x, target.y) === 0) { if (TILE_DEFS[item.placesTile].growTime) next.plant(target.x, target.y, item.placesTile); else next.set(target.x, target.y, item.placesTile); } }); if (!committed) addItem(inventory, slot.itemId, 1); else notify(`Placed ${item.name}.`); savePlayerState(); }
function buy(offer) { if (!offer) return; if (countItem(inventory, "gems") < offer.cost) { notify("Not enough Sky Gems."); return; } removeItem(inventory, "gems", offer.cost); if (!addItem(inventory, offer.item, offer.amount)) { addItem(inventory, "gems", offer.cost); notify("Your inventory is full."); return; } notify(`Bought ${offer.amount}× ${ITEM_DEFS[offer.item].name}.`); savePlayerState(); }
function updateCamera(delta) { const desiredX = player.x + player.width / 2 - canvas.width / 2, desiredY = player.y + player.height / 2 - canvas.height * .58, maxX = Math.max(0, WORLD_WIDTH * TILE_SIZE - canvas.width), maxY = Math.max(0, WORLD_HEIGHT * TILE_SIZE - canvas.height); camera.x += (Math.max(0, Math.min(maxX, desiredX)) - camera.x) * Math.min(1, delta * 6); camera.y += (Math.max(0, Math.min(maxY, desiredY)) - camera.y) * Math.min(1, delta * 6); }
function drawWorld() { drawSky(context, assets, camera, canvas.width, canvas.height); const startX = Math.max(0, Math.floor(camera.x / TILE_SIZE) - 1), endX = Math.min(WORLD_WIDTH, Math.ceil((camera.x + canvas.width) / TILE_SIZE) + 1), startY = Math.max(0, Math.floor(camera.y / TILE_SIZE) - 1), endY = Math.min(WORLD_HEIGHT, Math.ceil((camera.y + canvas.height) / TILE_SIZE) + 1); for (let y = startY; y < endY; y += 1) for (let x = startX; x < endX; x += 1) drawTile(context, assets, world.getBackground(x, y), x * TILE_SIZE - camera.x, y * TILE_SIZE - camera.y, TILE_SIZE, true); for (let y = startY; y < endY; y += 1) for (let x = startX; x < endX; x += 1) drawTile(context, assets, world.get(x, y), x * TILE_SIZE - camera.x, y * TILE_SIZE - camera.y); Object.entries(remotePlayers).forEach(([uid, remote]) => { if (uid !== user.uid && Date.now() - remote.updatedAt < 30000) drawPlayer(context, { x: remote.x, y: remote.y, width: 22, height: 40, facing: remote.facing || 1 }, camera, remote.username, true); }); drawPlayer(context, player, camera, username); const target = tileTarget(); drawCrosshair(context, target, camera, target.reachable); drawHotbar(context, assets, inventory, selectedSlot, canvas.width, canvas.height); drawHud(context, assets, { inventory, selectedSlot, toast, target, breaking, worldName: requestedName, online: Object.keys(remotePlayers).length }, canvas.width); shopLayout = shopOpen ? drawShop(context, assets, inventory, canvas.width, canvas.height) : null; }
function frame(now) { if (!running) return; const delta = Math.min(.033, (now - lastFrame) / 1000 || 0); lastFrame = now; if (!shopOpen) updatePlayer(player, world, input, delta); input.jumpPressed = false; updateCamera(delta); updateBreaking(now, tileTarget()); toast.timeLeft = Math.max(0, toast.timeLeft - delta); if (now - lastPlayerSave > 250) { lastPlayerSave = now; savePlayerState(); updatePresence(); } if (now - lastPlantCheck > 1500 && !pendingWorldChange) { lastPlantCheck = now; mutateWorld((next) => next.updatePlants()); } drawWorld(); requestAnimationFrame(frame); }
async function enterWorld() { if (!worldKey || !/^[a-z0-9_-]{3,28}$/.test(worldKey)) { fail("This world name is invalid. Return to the World Gate and enter a valid name."); return; } const profile = (await get(ref(database, `users/${user.uid}/profile`))).val(); username = profile?.username ?? "Explorer"; worldStateRef = ref(database, `worlds/${worldKey}/state`); playerStateRef = ref(database, `users/${user.uid}/worlds/${worldKey}`); presenceRef = ref(database, `worlds/${worldKey}/presence/${user.uid}`); await runTransaction(ref(database, `worlds/${worldKey}/meta`), (current) => current ?? { name: requestedName, key: worldKey, ownerId: user.uid, createdAt: Date.now() }); await runTransaction(worldStateRef, (current) => current ?? generateWorld().serialize()); const savedPlayer = (await get(playerStateRef)).val(); world = World.fromSave((await get(worldStateRef)).val()) ?? generateWorld(); inventory = createInventory(savedPlayer?.inventory); const surface = world.surface[18] || 39; player = createPlayer(savedPlayer?.player?.x ?? 18 * TILE_SIZE, savedPlayer?.player?.y ?? (surface - 3) * TILE_SIZE); selectedSlot = Math.min(Math.max(0, savedPlayer?.selectedSlot ?? 0), HOTBAR_SIZE - 1); onValue(worldStateRef, (snapshot) => { const next = World.fromSave(snapshot.val()); if (next) world = next; }); onValue(ref(database, `worlds/${worldKey}/presence`), (snapshot) => { remotePlayers = snapshot.val() ?? {}; }); await onDisconnect(presenceRef).remove(); await updatePresence(); await update(ref(database, `users/${user.uid}`), { lastWorld: worldKey, lastSeenAt: Date.now() }); assets = await loadAssets(); resize(); running = true; loadingCard.classList.add("is-hidden"); lastFrame = performance.now(); requestAnimationFrame(frame); }

window.addEventListener("resize", resize); window.addEventListener("beforeunload", () => { savePlayerState(); });
window.addEventListener("keydown", (event) => { if (["ArrowLeft", "ArrowRight", "ArrowUp", " "].includes(event.key)) event.preventDefault(); if (event.key === "a" || event.key === "ArrowLeft") input.left = true; if (event.key === "d" || event.key === "ArrowRight") input.right = true; if ((event.key === "w" || event.key === "ArrowUp" || event.key === " ") && !event.repeat) input.jumpPressed = true; if (/^[1-8]$/.test(event.key)) selectedSlot = Number(event.key) - 1; if ((event.key === "e" || event.key === "E") && !event.repeat) placeSelected(); if (event.key === "Escape") setShopOpen(false); });
window.addEventListener("keyup", (event) => { if (event.key === "a" || event.key === "ArrowLeft") input.left = false; if (event.key === "d" || event.key === "ArrowRight") input.right = false; });
canvas.addEventListener("pointermove", pointerPosition); canvas.addEventListener("pointerdown", (event) => { pointerPosition(event); canvas.focus(); if (!running) return; if (shopOpen) { buy(shopOfferAt(input.pointer, shopLayout)); return; } if (event.button === 0 || event.pointerType === "touch") { input.pointerDown = true; canvas.setPointerCapture?.(event.pointerId); } }); canvas.addEventListener("pointerup", () => { input.pointerDown = false; stopBreaking(); }); canvas.addEventListener("pointercancel", () => { input.pointerDown = false; stopBreaking(); }); canvas.addEventListener("contextmenu", (event) => { event.preventDefault(); placeSelected(); });
shopButton.addEventListener("click", () => setShopOpen(!shopOpen)); leaveButton.addEventListener("click", async () => { await savePlayerState(); await remove(presenceRef).catch(() => {}); window.location.assign("hub.html"); });
document.querySelectorAll("[data-control]").forEach((button) => { const control = button.dataset.control, down = (event) => { event.preventDefault(); if (control === "jump") input.jumpPressed = true; else if (control === "place") placeSelected(); else input[control] = true; }, up = (event) => { event.preventDefault(); if (control === "left" || control === "right") input[control] = false; }; button.addEventListener("pointerdown", down); button.addEventListener("pointerup", up); button.addEventListener("pointercancel", up); button.addEventListener("pointerleave", up); });
if (!firebaseConfigured) fail("Add your Firebase project settings to firebase-config.js, then refresh."); else onAuthStateChanged(auth, (nextUser) => { if (!nextUser) window.location.replace("index.html"); else { user = nextUser; enterWorld().catch((error) => fail(error.message)); } });
