import { loadAssets } from "./assets.js";
import { HOTBAR_SIZE, INVENTORY_SIZE, MAX_INVENTORY_SIZE, PHYSICS, REACH, TILE_SIZE, WORLD_HEIGHT, WORLD_WIDTH } from "./config.js";
import { CLAY_CROP_TILE, FLOWER_SEED_RECIPES, ITEM_DEFS, TILE_DEFS } from "./definitions.js";
import { addItem, countItem, createInventory, removeItem } from "./inventory.js";
import { createPlayer, playerOverlapsTile, updatePlayer } from "./player.js";
import { drawCrosshair, drawHotbar, drawHud, drawInventoryPanel, drawPlayer, drawShop, drawSky, drawTile, shopOfferAt } from "./ui.js";
import { World, generateWorld } from "./world.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import { get, onDisconnect, onValue, ref, remove, runTransaction, set, update } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-database.js";
import { auth, database, firebaseConfigured } from "./firebase.js";

const canvas = document.querySelector("#game");
const context = canvas.getContext("2d");
const loadingCard = document.querySelector("#loading-card");
const loadingTitle = document.querySelector("#loading-title");
const loadingMessage = document.querySelector("#loading-message");
const leaveButton = document.querySelector("#leave-button");
const shopButton = document.querySelector("#shop-button");
const bagButton = document.querySelector("#bag-button");
const params = new URLSearchParams(window.location.search);
const worldKey = params.get("world");
const requestedName = params.get("name") || worldKey;
let assets, world, inventory, inventorySize = INVENTORY_SIZE, player, user, username = "Explorer", worldStateRef, playerStateRef, presenceRef, gamePresenceRef, metaRef, inventoryRef, worldLockedBy = null;
let running = false, lastFrame = 0, lastPlayerSave = 0, lastPlantCheck = 0, selectedSlot = 0, shopOpen = false, shopLayout = null, inventoryOpen = false, invLayout = null, pendingWorldChange = false, remotePlayers = {};
const drag = { from: -1 };
const camera = { x: 0, y: 0 };
const ZOOM_MIN = .6, ZOOM_MAX = 2.5;
let zoom = 1;
function setZoom(next) { zoom = Math.min(ZOOM_MAX, Math.max(ZOOM_MIN, next)); }
const input = { left: false, right: false, jumpPressed: false, pointerDown: false, pointer: { x: 0, y: 0 } };
const breaking = { active: false, x: -1, y: -1, startedAt: 0, progress: 0 };
const toast = { message: "", timeLeft: 0 };
const lava = { hits: 0, lastHitAt: 0 };

function fail(message) { loadingTitle.textContent = "Could not enter world"; loadingMessage.textContent = message; loadingCard.classList.remove("is-hidden"); }
function notify(message) { toast.message = message; toast.timeLeft = 2.4; }
function resize() { canvas.width = Math.max(320, window.innerWidth); canvas.height = Math.max(320, window.innerHeight); context.imageSmoothingEnabled = false; }
function stopBreaking() { Object.assign(breaking, { active: false, progress: 0, x: -1, y: -1 }); }
const ONLINE_WINDOW = 30000;
function isFresh(entry) { return Boolean(entry) && Date.now() - (entry.updatedAt || 0) < ONLINE_WINDOW; }
function onlineCount() { let total = 1; Object.entries(remotePlayers).forEach(([uid, remote]) => { if (uid !== user?.uid && isFresh(remote)) total += 1; }); return total; }
function setShopOpen(open) { shopOpen = open; shopButton.setAttribute("aria-expanded", String(open)); shopButton.textContent = open ? "Close market" : "Sky Market"; stopBreaking(); }
function setInventoryOpen(open) { inventoryOpen = open; bagButton.setAttribute("aria-expanded", String(open)); if (open) stopBreaking(); }
function canBuild() { return !worldLockedBy || worldLockedBy === user?.uid; }
function respawnPoint() { const doorIndex = world.foreground.indexOf(6); if (doorIndex >= 0) return { x: (doorIndex % world.width) * TILE_SIZE + 5, y: Math.max(0, Math.floor(doorIndex / world.width) - 2) * TILE_SIZE }; const surface = world.surface[18] || 39; return { x: 18 * TILE_SIZE, y: (surface - 3) * TILE_SIZE }; }
async function leaveToWorldGate() { await savePlayerState(); await remove(presenceRef).catch(() => {}); await remove(gamePresenceRef).catch(() => {}); window.location.assign("hub.html"); }
function pointerPosition(event) { const bounds = canvas.getBoundingClientRect(); input.pointer.x = (event.clientX - bounds.left) * (canvas.width / bounds.width); input.pointer.y = (event.clientY - bounds.top) * (canvas.height / bounds.height); }
function tileTarget() { const worldX = input.pointer.x / zoom + camera.x, worldY = input.pointer.y / zoom + camera.y, x = Math.floor(worldX / TILE_SIZE), y = Math.floor(worldY / TILE_SIZE), inBounds = x >= 0 && x < WORLD_WIDTH && y >= 0 && y < WORLD_HEIGHT; const reachable = Math.hypot(x * TILE_SIZE + TILE_SIZE / 2 - (player.x + player.width / 2), y * TILE_SIZE + TILE_SIZE / 2 - (player.y + player.height / 2)) <= REACH; return { x, y, inBounds, reachable, tileId: inBounds ? world.get(x, y) : 0 }; }
function dropsFor(definition) { return (definition.harvest?.drops ?? definition.drops ?? []).map((drop) => { if (drop.chance && Math.random() > drop.chance) return null; let amount; if (drop.weighted) { const total = drop.weighted.reduce((sum, option) => sum + option.weight, 0); let roll = Math.random() * total; amount = drop.weighted[drop.weighted.length - 1].count; for (const option of drop.weighted) { roll -= option.weight; if (roll < 0) { amount = option.count; break; } } } else amount = drop.min ? Math.floor(Math.random() * (drop.max - drop.min + 1)) + drop.min : drop.count ?? 1; return { item: drop.item, amount }; }).filter(Boolean); }
function collectDrops(drops) { const collected = []; let inventoryFull = false; drops.forEach((drop) => { if (addItem(inventory, drop.item, drop.amount)) collected.push(drop); else inventoryFull = true; }); return { collected, inventoryFull }; }
function formatDrops(drops) { return drops.map((drop) => `${drop.amount}x ${ITEM_DEFS[drop.item].name}`).join(", "); }
async function mutateWorld(mutator) { if (pendingWorldChange) return false; pendingWorldChange = true; try { const result = await runTransaction(worldStateRef, (current) => { if (current) { const saved = World.fromSave(current); if (!saved) return; mutator(saved); return saved.serialize(); } const next = generateWorld(); mutator(next); return next.serialize(); }); const updatedWorld = World.fromSave(result.snapshot.val()); if (updatedWorld) world = updatedWorld; return result.committed; } catch { notify("World update failed. Check your connection."); return false; } finally { pendingWorldChange = false; } }
async function savePlayerState() { if (!player || !inventory) return; if (inventoryRef) await set(inventoryRef, { slots: inventory, size: inventorySize, selectedSlot, updatedAt: Date.now() }).catch(() => {}); if (playerStateRef) await set(playerStateRef, { player: { x: player.x, y: player.y }, worldName: requestedName, updatedAt: Date.now() }).catch(() => {}); }
async function updatePresence() { if (presenceRef && player) await set(presenceRef, { username, x: Math.round(player.x), y: Math.round(player.y), facing: player.facing, updatedAt: Date.now() }).catch(() => {}); if (gamePresenceRef) await set(gamePresenceRef, { world: worldKey, name: username, updatedAt: Date.now() }).catch(() => {}); }
async function completeBreak(target) { const definition = TILE_DEFS[target.tileId]; if (!definition || definition.unbreakable) return; const committed = await mutateWorld((next) => { if (next.get(target.x, target.y) === target.tileId) { next.set(target.x, target.y, 0); next.removePlant(target.x, target.y); next.naturalFlowers = (next.naturalFlowers ?? []).filter((flower) => flower.x !== target.x || flower.y !== target.y); } }); if (!committed) return; if (target.tileId === 7 && worldLockedBy === user?.uid && !world.foreground.includes(7)) { await runTransaction(metaRef, (current) => { if (!current) return current; const next = { ...current }; delete next.lockedBy; return next; }); worldLockedBy = null; notify("World lock removed — anyone can build here again."); } const { collected, inventoryFull } = collectDrops(dropsFor(definition)); const action = definition.harvest ? "Harvested" : "Mined"; notify(collected.length ? `${action} ${definition.name}: ${formatDrops(collected)}${inventoryFull ? " (inventory full)" : ""}` : `${action} ${definition.name}, but your inventory is full.`); await savePlayerState(); }
function updateBreaking(now, target) { if (!input.pointerDown || !target.inBounds || !target.reachable || !target.tileId || shopOpen || pendingWorldChange) { stopBreaking(); return; } if (!canBuild()) { stopBreaking(); return; } const definition = TILE_DEFS[target.tileId]; if (!definition || definition.unbreakable) { stopBreaking(); return; } if (!breaking.active || breaking.x !== target.x || breaking.y !== target.y) Object.assign(breaking, { active: true, x: target.x, y: target.y, startedAt: now, progress: 0 }); breaking.progress = (now - breaking.startedAt) / definition.breakTime; if (breaking.progress >= 1) { completeBreak(target); stopBreaking(); } }
async function placeSelected() { if (shopOpen || pendingWorldChange) return; const target = tileTarget(), slot = inventory[selectedSlot]; if (!target.inBounds || !target.reachable || !slot) return; const item = ITEM_DEFS[slot.itemId]; if (!item.placesTile) { notify("That item cannot be placed."); return; } if (!canBuild()) { notify("This world is locked — only the lock's owner can build here."); return; }
  const craftedSeed = FLOWER_SEED_RECIPES[item.placesTile];
  if (craftedSeed && target.y + 1 < WORLD_HEIGHT && world.get(target.x, target.y + 1) === CLAY_CROP_TILE) {
    if (target.tileId) { notify("That space is occupied."); return; }
    if (!removeItem(inventory, slot.itemId, 1)) return;
    const committed = await mutateWorld((next) => { if (next.get(target.x, target.y + 1) === CLAY_CROP_TILE) { next.set(target.x, target.y + 1, 0); next.removePlant(target.x, target.y + 1); } });
    if (committed) { addItem(inventory, craftedSeed, 1); notify(`Crafted ${ITEM_DEFS[craftedSeed].name}!`); }
    else addItem(inventory, slot.itemId, 1);
    savePlayerState();
    return;
  }
  if (target.tileId) { notify("That space is occupied."); return; } if (playerOverlapsTile(player, target.x, target.y)) { notify("Give yourself a little room."); return; } if (!removeItem(inventory, slot.itemId, 1)) return; const committed = await mutateWorld((next) => { if (next.get(target.x, target.y) === 0) { if (TILE_DEFS[item.placesTile].growTime) next.plant(target.x, target.y, item.placesTile); else next.set(target.x, target.y, item.placesTile); } }); if (!committed) { addItem(inventory, slot.itemId, 1); return; } if (item.placesTile === 7) { await runTransaction(metaRef, (current) => ({ ...(current ?? { name: requestedName, key: worldKey, ownerId: user.uid, createdAt: Date.now() }), lockedBy: user.uid })); worldLockedBy = user.uid; notify("World locked! Only you can build or break here now."); } else notify(`Placed ${item.name}.`); savePlayerState(); }
function updateCamera(delta) { const viewWidth = canvas.width / zoom, viewHeight = canvas.height / zoom, desiredX = player.x + player.width / 2 - viewWidth / 2, desiredY = player.y + player.height / 2 - viewHeight / 2, maxX = Math.max(0, WORLD_WIDTH * TILE_SIZE - viewWidth), maxY = Math.max(0, WORLD_HEIGHT * TILE_SIZE - viewHeight); camera.x += (Math.max(0, Math.min(maxX, desiredX)) - camera.x) * Math.min(1, delta * 6); camera.y += (Math.max(0, Math.min(maxY, desiredY)) - camera.y) * Math.min(1, delta * 6); }
function lavaContact() { const left = Math.floor((player.x + 3) / TILE_SIZE), right = Math.floor((player.x + player.width - 3) / TILE_SIZE), top = Math.floor((player.y + 3) / TILE_SIZE), bottom = Math.floor((player.y + player.height - 1) / TILE_SIZE); for (let y = top; y <= bottom; y += 1) for (let x = left; x <= right; x += 1) if (world.get(x, y) === 5) return { x, y }; return null; }
function checkLava(now) { const contact = lavaContact(); if (!contact || now - lava.lastHitAt < 800) return; lava.lastHitAt = now; lava.hits += 1; player.vy = -PHYSICS.jumpSpeed * .85; player.grounded = false; player.vx = (player.x + player.width / 2 >= contact.x * TILE_SIZE + TILE_SIZE / 2 ? 1 : -1) * PHYSICS.runSpeed * 1.4; if (lava.hits >= 4) { const spawn = respawnPoint(); player.x = spawn.x; player.y = spawn.y; player.vx = 0; player.vy = 0; lava.hits = 0; notify("The lava was too hot — you burned up and respawned at the door!"); savePlayerState(); } else notify(`Ouch! Lava burns! ${4 - lava.hits} lives left.`); }
function buy(offer) { if (!offer) return; if (countItem(inventory, "gems") < offer.cost) { notify("Not enough Sky Gems."); return; } if (offer.item === "inventory_slots") { if (inventorySize >= MAX_INVENTORY_SIZE) { notify("Your inventory is fully upgraded."); return; } removeItem(inventory, "gems", offer.cost); const before = inventory.length; inventorySize = Math.min(MAX_INVENTORY_SIZE, inventorySize + offer.amount); while (inventory.length < inventorySize) inventory.push(null); notify(`Bought ${inventorySize - before} more inventory slots!`); savePlayerState(); return; } removeItem(inventory, "gems", offer.cost); if (!addItem(inventory, offer.item, offer.amount)) { addItem(inventory, "gems", offer.cost); notify("Your inventory is full."); return; } notify(`Bought ${offer.amount}× ${ITEM_DEFS[offer.item].name}.`); savePlayerState(); }
function moveInventorySlot(from, to) { if (from === to) return; const source = inventory[from], target = inventory[to]; if (!source) return; if (!target) { inventory[to] = source; inventory[from] = null; } else if (target.itemId === source.itemId) { const total = Math.min(999, source.count + target.count); const moved = total - target.count; target.count = total; source.count -= moved; if (source.count <= 0) inventory[from] = null; } else { inventory[to] = source; inventory[from] = target; } savePlayerState(); }
function drawWorld() { drawSky(context, assets, camera, canvas.width, canvas.height); const viewWidth = canvas.width / zoom, viewHeight = canvas.height / zoom; const startX = Math.max(0, Math.floor(camera.x / TILE_SIZE) - 1), endX = Math.min(WORLD_WIDTH, Math.ceil((camera.x + viewWidth) / TILE_SIZE) + 1), startY = Math.max(0, Math.floor(camera.y / TILE_SIZE) - 1), endY = Math.min(WORLD_HEIGHT, Math.ceil((camera.y + viewHeight) / TILE_SIZE) + 1); context.save(); context.scale(zoom, zoom); for (let y = startY; y < endY; y += 1) for (let x = startX; x < endX; x += 1) drawTile(context, assets, world.get(x, y), x * TILE_SIZE - camera.x, y * TILE_SIZE - camera.y); Object.entries(remotePlayers).forEach(([uid, remote]) => { if (uid !== user.uid && isFresh(remote)) drawPlayer(context, { x: remote.x, y: remote.y, width: 22, height: 40, facing: remote.facing || 1 }, camera, remote.username, true); }); drawPlayer(context, player, camera, username); const target = tileTarget(); drawCrosshair(context, target, camera, target.reachable); context.restore(); drawHotbar(context, assets, inventory, selectedSlot, canvas.width, canvas.height); drawHud(context, assets, { inventory, selectedSlot, toast, target, breaking, worldName: requestedName, online: onlineCount(), lavaHits: lava.hits }, canvas.width); invLayout = inventoryOpen ? drawInventoryPanel(context, assets, inventory, selectedSlot, canvas.width, canvas.height, drag.from >= 0 ? { from: drag.from, pointer: input.pointer } : null) : null; shopLayout = shopOpen ? drawShop(context, assets, inventory, canvas.width, canvas.height) : null; }
function frame(now) { if (!running) return; const delta = Math.min(.033, (now - lastFrame) / 1000 || 0); lastFrame = now; if (!shopOpen) { updatePlayer(player, world, input, delta); checkLava(now); } input.jumpPressed = false; updateCamera(delta); updateBreaking(now, tileTarget()); toast.timeLeft = Math.max(0, toast.timeLeft - delta); if (now - lastPlayerSave > 250) { lastPlayerSave = now; savePlayerState(); updatePresence(); } if (now - lastPlantCheck > 1500 && !pendingWorldChange) { lastPlantCheck = now; mutateWorld((next) => { next.updatePlants(); next.updateFlowers(); }); } drawWorld(); requestAnimationFrame(frame); }
async function enterWorld() { if (!worldKey || !/^[a-z0-9_-]{3,28}$/.test(worldKey)) { fail("This world name is invalid. Return to the World Gate and enter a valid name."); return; } const profile = (await get(ref(database, `users/${user.uid}/profile`))).val(); username = profile?.username ?? user.displayName ?? user.email?.split("@")[0] ?? "Explorer"; worldStateRef = ref(database, `worlds/${worldKey}/state`); playerStateRef = ref(database, `users/${user.uid}/worlds/${worldKey}`); inventoryRef = ref(database, `users/${user.uid}/inventory`); presenceRef = ref(database, `worlds/${worldKey}/presence/${user.uid}`); gamePresenceRef = ref(database, `gamePresence/${user.uid}`); metaRef = ref(database, `worlds/${worldKey}/meta`); await runTransaction(metaRef, (current) => current ?? { name: requestedName, key: worldKey, ownerId: user.uid, createdAt: Date.now() }); worldLockedBy = ((await get(metaRef)).val() ?? {}).lockedBy ?? null; await runTransaction(worldStateRef, (current) => current ?? generateWorld().serialize()); const savedPlayer = (await get(playerStateRef)).val(); world = World.fromSave((await get(worldStateRef)).val()) ?? generateWorld(); const savedInventory = (await get(inventoryRef)).val(); inventorySize = Math.max(INVENTORY_SIZE, Math.min(MAX_INVENTORY_SIZE, Math.floor(savedInventory?.size ?? savedPlayer?.inventorySize) || INVENTORY_SIZE)); inventory = createInventory(savedInventory?.slots ?? savedPlayer?.inventory, inventorySize); let grantedDoor = false; if (!world.foreground.includes(6) && !inventory.some((slot) => slot?.itemId === "white_door")) { addItem(inventory, "white_door", 1); grantedDoor = true; } const spawn = respawnPoint(); player = createPlayer(savedPlayer?.player?.x ?? spawn.x, savedPlayer?.player?.y ?? spawn.y); selectedSlot = Math.min(Math.max(0, savedInventory?.selectedSlot ?? savedPlayer?.selectedSlot ?? 0), INVENTORY_SIZE - 1); onValue(worldStateRef, (snapshot) => { const next = World.fromSave(snapshot.val()); if (next) world = next; }); onValue(ref(database, `worlds/${worldKey}/presence`), (snapshot) => { remotePlayers = snapshot.val() ?? {}; }); await onDisconnect(presenceRef).remove(); await onDisconnect(gamePresenceRef).remove(); await updatePresence(); await update(ref(database, `users/${user.uid}`), { lastWorld: worldKey, lastSeenAt: Date.now() }); assets = await loadAssets(); resize(); running = true; loadingCard.classList.add("is-hidden"); if (grantedDoor) notify("You received a White Door — place it anywhere. Click it to return to the World Gate!"); else if (worldLockedBy && worldLockedBy !== user.uid) notify("This world is locked — you can look around but not build."); lastFrame = performance.now(); requestAnimationFrame(frame); }

window.addEventListener("resize", resize); window.addEventListener("beforeunload", () => { savePlayerState(); });
window.addEventListener("keydown", (event) => { if (["ArrowLeft", "ArrowRight", "ArrowUp", " "].includes(event.key)) event.preventDefault(); if (event.key === "a" || event.key === "ArrowLeft") input.left = true; if (event.key === "d" || event.key === "ArrowRight") input.right = true; if ((event.key === "w" || event.key === "ArrowUp" || event.key === " ") && !event.repeat) input.jumpPressed = true; if (/^[1-5]$/.test(event.key)) selectedSlot = Number(event.key) - 1; if ((event.key === "e" || event.key === "E") && !event.repeat) placeSelected(); if ((event.key === "i" || event.key === "I") && !event.repeat) setInventoryOpen(!inventoryOpen); if (event.key === "+" || event.key === "=") setZoom(zoom * 1.15); if (event.key === "-" || event.key === "_") setZoom(zoom / 1.15); if (event.key === "Escape") { setShopOpen(false); setInventoryOpen(false); } });
window.addEventListener("keyup", (event) => { if (event.key === "a" || event.key === "ArrowLeft") input.left = false; if (event.key === "d" || event.key === "ArrowRight") input.right = false; });
window.addEventListener("pointerup", (event) => { if (drag.from < 0) return; pointerPosition(event); const hit = inventoryOpen && invLayout ? invLayout.slots.find((slot) => input.pointer.x >= slot.x && input.pointer.x <= slot.x + slot.size && input.pointer.y >= slot.y && input.pointer.y <= slot.y + slot.size) : null; if (hit && hit.index !== drag.from) moveInventorySlot(drag.from, hit.index); drag.from = -1; });
canvas.addEventListener("pointermove", pointerPosition); canvas.addEventListener("pointerdown", (event) => { pointerPosition(event); canvas.focus(); if (!running) return; if (shopOpen) { buy(shopOfferAt(input.pointer, shopLayout)); return; } if (inventoryOpen) { if (invLayout) { const hit = invLayout.slots.find((slot) => input.pointer.x >= slot.x && input.pointer.x <= slot.x + slot.size && input.pointer.y >= slot.y && input.pointer.y <= slot.y + slot.size); if (hit) { drag.from = hit.index; selectedSlot = hit.index; } else if (input.pointer.x < invLayout.x || input.pointer.x > invLayout.x + invLayout.width || input.pointer.y < invLayout.y || input.pointer.y > invLayout.y + invLayout.height) setInventoryOpen(false); } return; } if (event.button === 0 || event.pointerType === "touch") { const target = tileTarget(); if (target.tileId === 6 && target.reachable) { leaveToWorldGate(); return; } input.pointerDown = true; canvas.setPointerCapture?.(event.pointerId); } }); canvas.addEventListener("pointerup", () => { input.pointerDown = false; stopBreaking(); }); canvas.addEventListener("pointercancel", () => { input.pointerDown = false; stopBreaking(); }); canvas.addEventListener("contextmenu", (event) => { event.preventDefault(); placeSelected(); });
canvas.addEventListener("wheel", (event) => { event.preventDefault(); setZoom(zoom * (event.deltaY < 0 ? 1.12 : 1 / 1.12)); }, { passive: false });
shopButton.addEventListener("click", () => setShopOpen(!shopOpen)); bagButton.addEventListener("click", () => setInventoryOpen(!inventoryOpen)); leaveButton.addEventListener("click", leaveToWorldGate);
document.querySelectorAll("[data-control]").forEach((button) => { const control = button.dataset.control, down = (event) => { event.preventDefault(); if (control === "jump") input.jumpPressed = true; else if (control === "place") placeSelected(); else input[control] = true; }, up = (event) => { event.preventDefault(); if (control === "left" || control === "right") input[control] = false; }; button.addEventListener("pointerdown", down); button.addEventListener("pointerup", up); button.addEventListener("pointercancel", up); button.addEventListener("pointerleave", up); });
if (!firebaseConfigured) fail("Add your Firebase project settings to firebase-config.js, then refresh."); else onAuthStateChanged(auth, (nextUser) => { if (!nextUser) window.location.replace("index.html"); else { user = nextUser; enterWorld().catch((error) => fail(error.message)); } });
