import assert from 'node:assert/strict';
import { ADMIN_UID, isAdminAccount } from '../admin.js';
import { ITEM_DEFS, TILE_DEFS } from '../definitions.js';
import { applyNpcOffer, grantItems, normalizeNpc, quantity, npcAtPoint } from '../npcs.js';
import { countItem, createInventory } from '../inventory.js';

assert.equal(isAdminAccount({uid: ADMIN_UID}), true);
assert.equal(isAdminAccount({uid: 'someone-else', displayName: 'admin', role: 'admin'}), false);
assert.equal(isAdminAccount({uid: ADMIN_UID}, true), false);
for (const id of Object.keys(TILE_DEFS)) if (Number(id)) assert.ok(Object.values(ITEM_DEFS).some(item => item.placesTile === Number(id)), `Tile ${id} can be granted`);
const full = [{itemId:'rock',count:999},{itemId:'dirt_block',count:999}];
const granted = grantItems(full, 'snow_block', 1000000);
assert.equal(granted.length, 3);
assert.equal(countItem(createInventory(granted, 3), 'snow_block'), 1000000, 'Unlimited stack survives reload');
assert.deepEqual(full, [{itemId:'rock',count:999},{itemId:'dirt_block',count:999}], 'Grant stages without changing original');
const sparse = createInventory({'12':{itemId:'rock',count:5000}},20);
assert.equal(sparse[12].count,5000,'Firebase sparse slot maps preserve admin grants');
assert.equal(sparse[0],null,'Sparse map does not give starter items');
for (const n of [0, -1, 1.5, Infinity, Number.MAX_SAFE_INTEGER+1]) assert.throws(() => quantity(n));

const bag = {slots:[{itemId:'rock',count:5},null],size:2};
const offer = {requires:[{itemId:'rock',amount:2},{itemId:'rock',amount:3}],rewards:[{itemId:'gems',amount:10}],repeatable:false};
const after = applyNpcOffer(bag, offer, 'world_npc_action', 'request-1');
assert.equal(countItem(after.slots,'rock'),0);
assert.equal(countItem(after.slots,'gems'),10);
assert.deepEqual(bag.slots,[{itemId:'rock',count:5},null], 'Payment leaves source unchanged');
assert.deepEqual(applyNpcOffer(after, offer, 'world_npc_action', 'request-1'), after, 'Same request cannot charge twice');
assert.throws(() => applyNpcOffer(after, offer, 'world_npc_action', 'request-2'), /already completed/);
assert.deepEqual(applyNpcOffer(bag, offer, 'world_npc_action', 'request-1').slots,after.slots,'Retry callback repeats exactly the same transform');
const failed = structuredClone(bag);
assert.throws(() => applyNpcOffer(failed,{...offer,rewards:[{itemId:'gems',amount:10},{itemId:'moon_seed',amount:999},{itemId:'clay_seed',amount:999}]},'claim','req'), /Make room/);
assert.deepEqual(failed,bag,'Failure after staging multiple rewards returns all payment');
assert.throws(() => applyNpcOffer({slots:[{itemId:'rock',count:4}],size:1},offer,'claim','req'), /need 5/);
const repeatOffer = {...offer,repeatable:true};
const repeated = applyNpcOffer({slots:[{itemId:'rock',count:10},null],size:2},repeatOffer,'repeat','1');
const twice = applyNpcOffer(repeated,repeatOffer,'repeat','2');
assert.equal(countItem(twice.slots,'gems'),20);
assert.equal(countItem(twice.slots,'rock'),0);
const info = applyNpcOffer(bag,{requires:[{itemId:'rock',amount:1}],rewards:[],repeatable:true},'info','request');
assert.equal(countItem(info.slots,'rock'),4,'Payment can unlock information without an item reward');
const free = applyNpcOffer(bag,{requires:[],rewards:[{itemId:'gems',amount:7}],repeatable:true},'free','request');
assert.equal(countItem(free.slots,'gems'),7,'Free reward action');
const npc = normalizeNpc({name:'Guide',x:10,y:15,dialogue:'Hello\nWelcome!',offers:{test:{label:'Trade',repeatable:true,requires:offer.requires,rewards:offer.rewards}}});
assert.equal(npc.offers.test.requires.length,1);
assert.deepEqual(normalizeNpc(JSON.parse(JSON.stringify(npc))),npc,'NPC definitions survive persistence');
assert.equal(npcAtPoint({test:npc},{x:10*32+16,y:15*32+16})[0],'test');
assert.equal(npcAtPoint({test:{...npc,enabled:false}},{x:10*32+16,y:15*32+16}),undefined);
assert.throws(() => normalizeNpc({name:'Guide',x:128,y:15}), /inside/);
console.log('Admin identity, all tiles, unlimited grants, atomic multiple-item trades, payment-only info, free rewards, repeat/once receipts and persistence passed.');
